taxiserver/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('core.views',
    url(r'^$', 'home', name='home'),
    url(r'^meu-local$', 'meu_local', name='meu_local'),
    url(r'^minhas-solicitacoes-pendentes$', 'taxi_solicitacoes_pendentes', name='taxi_solicitacoes_pendentes'),
    url(r'^minhas-solicitacoes-atendidas$', 'taxi_solicitacoes_atendidas', name='taxi_solicitacoes_atendidas'),
    url(r'^alterar-minha-situacao$', 'taxi_alterar_minha_situacao', name='taxi_alterar_minha_situacao'),
    url(r'^solicitacao/(?P<solicitacao_id>\d+)/$', 'taxi_solicitacao', name='taxi_solicitacao'),
    url(r'^solicitacao-alterar-situacao/(?P<solicitacao_id>\d+)/$', 'taxi_solicitacao_alterar_situacao', name='taxi_solicitacao_alterar_situacao'),
    url(r'^taxi/buscar/(?P<taxi_id>\d+)/$', 'taxi_buscar', name='taxi_buscar'),
    url(r'^taxi/livres/$', 'taxi_livres', name='taxi_livres'),
    url(r'^taxi/ocupados/$', 'taxi_ocupados', name='taxi_ocupados'),
    url(r'^taxi/alterar-situacao/(?P<taxi_id>\d+)/$', 'taxi_alterar_situacao', name='taxi_alterar_situacao'),
    url(r'^taxi/alterar-posicao/(?P<taxi_id>\d+)/(?P<latitude>[\w|\W]+)/(?P<longitude>[\w|\W]+)$', 'taxi_alterar_posicao', name='taxi_alterar_posicao'),
    url(r'^taxi/solicitacoes/(?P<taxi_id>\d+)/$', 'solicitacoes_taxi', name='solicitacoes_taxi'),
    url(r'^taxi/solicitacao/atender/(?P<solicitacao_id>\d+)/$', 'solicitacao_atender', name='solicitacao_atender'),
    url(r'^usuario/criar', 'usuario_criar', name='usuario_criar'),
    url(r'^usuario/buscar/(?P<usuario_id>\d+)/$', 'usuario_buscar', name='usuario_buscar'),
    url(r'^usuario/solicitacao/criar', 'solicitacao_criar', name='solicitacao_criar'),
    url(r'^usuario/solicitacoes/(?P<usuario_id>\d+)/$', 'solicitacoes_usuario', name='solicitacoes_usuario'),
    url(r'^usuario/login', 'usuario_verificar_login', name='usuario_verificar_login'),
    url(r'^solicitacao/excluir/(>P<solicitacao_id>\d+)/$', 'solicitacao_excluir', name='solicitacao_excluir'),
    # Examples:
    # url(r'^$', 'taxiserver.views.home', name='home'),
    # url(r'^taxiserver/', include('taxiserver.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('',
    url(r'^accounts/login/$', 'django.contrib.auth.views.login',{'template_name':'accounts/login.html'}, name='login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', name='logout'),
    url(r'^password_change/$', 'django.contrib.auth.views.password_change', {'template_name':'accounts/password_change.html'}, name='password_change'),
    url(r'^password_change/done/$', 'django.contrib.auth.views.password_change_done', name='password_change_done'),
    url(r'^password_reset/$', 'django.contrib.auth.views.password_reset', {'template_name':'accounts/password_reset.html'}, name='password_reset'),
    url(r'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    url(r'^reset/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'django.contrib.auth.views.password_reset_confirm',
        name='password_reset_confirm'),
    url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),
)

from django.conf import settings
urlpatterns += patterns('django.views.static',
    url(r'^static/(?P<path>.*)$', 'serve',
        {'document_root': settings.STATIC_ROOT}),
)

core/models.py
# coding: utf-8
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.utils.translation import ugettext_lazy as _

#USUARIO
class UserManager(BaseUserManager):
    def create_user(self, nome, telefone, email, password):
        user = self.model(
            nome        = nome,
            email       = email,
            password    = password,
            telefone    = telefone
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        user = self.create_user(self, email, password)
        user.is_active = True
        user.save(using=self._db)
        return user

class Usuario(AbstractBaseUser):
    USERNAME_FIELD = 'email'

    objects = UserManager()
    
    def has_module_perms(self, app_label):
        return True

    def has_perm(self, perm, obj=None):
        return True

    def get_short_name(self):
        return self.nome[0:10]

    def get_full_name(self):
        return self.nome

    def is_staff(self):
        return self.is_staff

    nome        =   models.CharField(_('nome'), max_length=70)
    email       =   models.EmailField(_('email'), unique=True, max_length=70, db_index=True)
    telefone    =   models.CharField(_('telefone'), max_length=14)

    class Meta:
        ordering            =   [u'nome']
        verbose_name        =   _(u'usuário')
        verbose_name_plural =   _(u'usuários')

    def __unicode__(self):
        return self.nome

    @property
    def get_dados(self):
        qs_taxi = Taxi.objects.filter(usuario=self)
        if qs_taxi:
            return u"Veículo: %s - Taxista: %s" % (qs_taxi[0].veiculo, self.get_short_name())
        return ""

    @property
    def get_situacao(self):
        return Taxi.objects.get(usuario=self).get_situacao

    @property
    def get_taxi_id(self):
        return Taxi.objects.get(usuario=self).pk

    @property
    def get_latitude(self):
        taxi = Taxi.objects.get(usuario=self)
        return taxi.latitude

    @property
    def get_longitude(self):
        taxi = Taxi.objects.get(usuario=self)
        return taxi.longitude

#TAXI
class Taxi(models.Model):

    SITUACOES = (
        ('L',_('Livre')),
        ('O',_('Ocupado')),
    )

    veiculo     = models.CharField(_('veiculo'), max_length=70)
    usuario     = models.ForeignKey('Usuario', unique=True)
    latitude    = models.CharField(_('latitude'), max_length=20)
    longitude   = models.CharField(_('longitude'), max_length=20)
    situacao    = models.CharField(_(u'situação'), max_length=1, choices=SITUACOES)

    class Meta:
        ordering               = [u'usuario', u'veiculo']
        verbose_name           =   _(u'taxi')
        verbose_name_plural    =   _(u'taxi')

    def __unicode__(self):
        return self.usuario.nome+' - '+self.veiculo

    @property
    def get_situacao(self):
        if self.situacao=='O':
            return u"Ocupado"
        else:
            return u"Livre"

#SOLICITACAO
class Solicitacao(models.Model):
    data_solicitacao    = models.DateTimeField(_('data da solicitação'), auto_now_add=True)
    data_conclusao      = models.DateTimeField(_('data da conclusão'), null=True, blank=True)
    usuario             = models.ForeignKey('Usuario')
    taxi                = models.ForeignKey('Taxi')
    latitude            = models.CharField(_('latitude'), max_length=20)
    longitude           = models.CharField(_('longitude'), max_length=20)

    class Meta:
        ordering            =   [u'data_solicitacao']
        verbose_name        =   _(u'solicitação')
        verbose_name_plural =   _(u'solicitações')

    def __unicode__(self):
        return self.data_solicitacao.strftime("%d/%m/%Y %H:%M:%S")+' - '+self.usuario.nome+' - '+self.taxi.veiculo

core/views.py
# coding: utf-8
from datetime import datetime, timedelta
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import check_password
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
from models import *

#HOME
@login_required
def home(request):
    return render(request,'base.html')

#MEU LOCAL
@login_required
def meu_local(request):
    return render(request,'meu_local.html')

#SOLICITACOES PENDENTES DO TAXI
@login_required
def taxi_solicitacoes_pendentes(request):
    ls = Solicitacao.objects.filter(taxi=Taxi.objects.get(usuario=request.user), data_conclusao__isnull=True)
    return render(request, 'taxi_solicitacoes_pendentes.html', {'ls':ls})

#SOLICITACOES ATENDIDAS DO TAXI
@login_required
def taxi_solicitacoes_atendidas(request):
    ls = Solicitacao.objects.filter(taxi=Taxi.objects.get(usuario=request.user), data_conclusao__isnull=False)
    return render(request, 'taxi_solicitacoes_atendidas.html', {'ls':ls})

@login_required
def taxi_solicitacao(request,solicitacao_id):
    return render(request, 'taxi_solicitacao.html', {'solicitacao':Solicitacao.objects.get(id=solicitacao_id)})

@login_required
def taxi_solicitacao_alterar_situacao(request,solicitacao_id):
    solicitacao = Solicitacao.objects.get(pk=solicitacao_id)
    if solicitacao.data_conclusao:
        solicitacao.data_conclusao = None
    else:
        solicitacao.data_conclusao = datetime.now()
    solicitacao.save()
    return taxi_solicitacoes_pendentes(request)

def taxi_alterar_minha_situacao(request):
    taxi = Taxi.objects.get(usuario=request.user)
    if taxi.situacao == 'L':
        taxi.situacao = 'O'
    else:
        taxi.situacao = 'L'
    taxi.save()
    return home(request)


#TAXI
def taxi_buscar(request, taxi_id):
    try:
        return HttpResponse(serializers.serialize("json", Taxi.objects.filter(pk=taxi_id)), content_type="application/json")
    except Exception as e:
        return HttpResponse('{"resultado":"ERRO", "mensagem":'+e.message+'}', content_type="application/json")


def buscar_taxi_pela_situacao(situacao):
    return Taxi.objects.filter(situacao=situacao)

def taxi_livres(request):
    return HttpResponse(serializers.serialize("json", buscar_taxi_pela_situacao('L')), content_type="application/json")


def taxi_ocupados(request):
    return HttpResponse(serializers.serialize("json", buscar_taxi_pela_situacao('O')), content_type="application/json")

def taxi_alterar_situacao(request,taxi_id):
    try:
        taxi = Taxi.objects.get(pk=taxi_id)
        if taxi.situacao == 'L':
            taxi.situacao = 'O'
        else:
            taxi.situacao = 'L'

        taxi.save()

        return HttpResponse('{"resultado":"OK"}', content_type="application/json")
    except:
        return HttpResponse('{"resultado":"ERRO"}', content_type="application/json")


def taxi_alterar_posicao(request,taxi_id, latitude, longitude):
    try:
        taxi            = Taxi.objects.get(pk=taxi_id)
        taxi.latitude   = latitude
        taxi.longitude  = longitude
        taxi.save()

        return HttpResponse('{"resultado":"OK"}', content_type="application/json")
    except:
        return HttpResponse('{"resultado":"ERRO"}', content_type="application/json")


#USUARIO
@csrf_exempt
def usuario_criar(request):
    try:
        if request.method != 'POST':
            raise Exception(u'Nao eh um POST valido!')

        usu             = Usuario()
        usu.nome        = request.POST.get('nome')
        usu.email       = request.POST.get('email')
        usu.telefone    = request.POST.get('telefone')
        usu.set_password(request.POST.get('senha'))
        usu.save()

        return HttpResponse('{"resultado":"OK"}', content_type="application/json")
    except Exception as e:
        return HttpResponse('{"resultado":"ERRO", "mensagem":'+e.message+'}', content_type="application/json")

@csrf_exempt
def usuario_verificar_login(request):
    try:
        if request.method != 'POST':
            raise Exception(u'Nao eh um POST valido!')

        usu = Usuario.objects.get(email=request.POST.get('email'))

        if check_password(request.POST.get('senha'), usu.password):
            #localizar se usuario possui taxi
            taxi_id = 0
            ls_taxi = Taxi.objects.filter(usuario=usu)
            if len(ls_taxi):
                taxi_id = ls_taxi[0].id

            return HttpResponse('{"resultado":"OK", "id":"'+str(usu.id)+'","taxi_id":"'+str(taxi_id)+'"}', content_type="application/json")
        else:
            return HttpResponse('{"resultado":"ERRO", "mensagem":"Login ou senha invalidos"}', content_type="application/json")
    except Exception as e:
        return HttpResponse('{"resultado":"ERRO", "mensagem":"'+e.message+'"}', content_type="application/json")

def usuario_buscar(request, usuario_id):
    try:
        return HttpResponse(serializers.serialize("json", Usuario.objects.filter(pk=usuario_id)), content_type="application/json")
    except Exception as e:
        return HttpResponse('{"resultado":"ERRO", "mensagem":'+e.message+'}', content_type="application/json")


#SOLICITACAO
@csrf_exempt
def solicitacao_criar(request):
    try:
        if request.method != 'POST':
            raise Exception(u'Nao eh um POST valido!')

        sol             = Solicitacao()
        sol.usuario     = Usuario.objects.get(pk=request.POST.get('usuario_id'))
        sol.taxi        = Taxi.objects.get(pk=request.POST.get('taxi_id'))
        sol.latitude    = request.POST.get('latitude')
        sol.longitude   = request.POST.get('longitude')
        sol.save()

        return HttpResponse('{"resultado":"OK"}', content_type="application/json")
    except Exception as e:
        return HttpResponse('{"resultado":"ERRO", "mensagem":'+e.message+'}', content_type="application/json")

def solicitacao_excluir(request, solicitacao_id):
    try:
        sol = Solicitacao.objects.get(pk=solicitacao_id)
        sol.delete()
        return HttpResponse('{"resultado":"OK"}', content_type="application/json")
    except Exception as e:
        return HttpResponse('{"resultado":"ERRO", "mensagem":'+e.message+'}', content_type="application/json")

def solicitacoes_usuario(request, usuario_id):
    try:
        return HttpResponse(serializers.serialize("json", Solicitacao.objects.filter(usuario=usuario_id)), content_type="application/json")
    except Exception as e:
        return HttpResponse('{"resultado":"ERRO", "mensagem":'+e.message+'}', content_type="application/json")

def solicitacoes_taxi(request, taxi_id):
    try:
        return HttpResponse(serializers.serialize("json", Solicitacao.objects.filter(taxi=taxi_id)), content_type="application/json")
    except Exception as e:
        return HttpResponse('{"resultado":"ERRO", "mensagem":'+e.message+'}', content_type="application/json")

def solicitacao_atender(request, solicitacao_id):
    try:
        solicitacao = Solicitacao.objects.get(pk=solicitacao_id)
        solicitacao.data_conclusao = datetime.datetime.now()
        return HttpResponse('{"resultado":"OK"}', content_type="application/json")
    except Exception as e:
        return HttpResponse('{"resultado":"ERRO", "mensagem":'+e.message+'}', content_type="application/json")

core/templates/accounts/base.html
<!DOCTYPE html>
{% load bootstrap3 %}
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <title>Frontend Taxi</title>
    <meta name="description" content="">
    <meta name="author" content="Dylan Verheul">
    {% bootstrap_css %}
    
    <style type="text/css">
        body {
            padding-top: 60px;
        }

        h1{
            font-size:18px;
        }

        .glyphicon{
            font-size:30px;
            color: #000;
        }

        .navbar-btn{
            width:170px;
        }

        button span{
            color:#000;
        }
    </style>


    <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
    {% bootstrap_javascript %}
    {% block extra_head %}{% endblock %}
</head>

<body>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="brand" href="/" title="Taxi">
            <img class="img" src="{{ STATIC_URL }}img/logo-taxi.png" style="heigth:36px; width:36px;">
            <small style="color: #FFF; font-size:20px;">REDE TAXI</small>
        </a>
    </div>
</nav>

<nav class="navbar navbar-inverse navbar-fixed-bottom">
    <center>
        <button type="button" class="btn navbar-btn btn-warning" onClick="window.location='{% url 'taxi_solicitacoes_pendentes' %}'">
            <span class="glyphicon glyphicon-hand-right"></span><br />
            <span>Solicitações Pendentes</span>
        </button>
        <button type="button" class="btn navbar-btn btn-warning" onClick="window.location='{% url 'taxi_solicitacoes_atendidas' %}'">
            <span class="glyphicon glyphicon-chevron-down"></span><br />
            <span>Solicitações Atendidas</span>
        </button>
        <button type="button" class="btn navbar-btn btn-warning" onClick="window.location='{% url 'meu_local' %}'">
                <span class="glyphicon glyphicon-map-marker"></span><br />
                <span>Onde estou?</span>
        </button>
        <button type="button" class="btn navbar-btn btn-warning" onClick="window.location='{% url 'taxi_alterar_minha_situacao' %}'">
                <span class="glyphicon glyphicon-repeat"></span><br />
                <span>Alterar meu Status</span>
        </button>
    </center>
</nav>

<div class="container">
    <center>
            <img src="{{STATIC_URL}}img/logo-taxi.png">
            <br />
    </center>

    {% block content %}
       
    {% endblock %}
</div> <!-- container -->

</body>
</html>

core/templates/accounts/login.html
{% extends "accounts/base.html" %}

{% load bootstrap3 %}

{% block extra_head %}
    {{ form.media }}
    <style>

	</style>
{% endblock %}

{% block content %}
	<form class="form-vertical text-left" action="" method="post">
	    	{% csrf_token %}
	    	<center>
		    	<div class="fieldWrapper">
			        <label for="id_email">E-mail:</label><br />
			        {{ form.username }}
			        {% if form.username.errors %}
			        <div class="alert alert-danger">{{ form.username.errors }}</div>
			        {% endif %}
	    		</div>
	    		<br />
	    		<div class="fieldWrapper">
			        <label for="id_password">Senha:</label><br />
			        {{ form.password }}
			        {% if form.password.errors %}
			        <div class="alert alert-danger">{{ form.password.errors }}</div>
			        {% endif %}
	    		</div>
	    		<hr />
		    	<p>
			    	<button type="submit" class="btn btn-primary btn-small">
			    		<i class="icon-off icon-white"></i> Entrar
			    	</button>
		    		<br />
		        	<a href="{% url 'password_reset' %}" class="btn btn-small">
		            <i class="icon-lock"></i> Esqueci da minha senha
		        	</a>
		        </p>
		    </center>
	</form>
{% endblock %}

core/templates/accounts/password_change.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block extra_head %}
    {{ form.media }}
{% endblock %}

{% block content %}

<h1><i class="icon-lock"></i> Alterar senha de acesso</h1>

<form class="form-vertical" action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    
    <p class="form-actions">
        <button type="submit" class="btn btn-primary btn-small"><i class="icon-chevron-down icon-white"></i> Gravar</button>
    </p>
</form>

{% endblock %}

core/templates/accounts/password_reset.html
{% extends "accounts/base.html" %}
{% load bootstrap3 %}

{% block extra_head %}
    {{ form.media }}
{% endblock %}

{% block content %}

<h1><i class="icon-lock"></i> Alterar senha de acesso</h1>

<form class="form-vertical" action="" method="post">
    {% csrf_token %}
    {{ form }}
    
    <p class="form-actions">
        <button type="submit" class="btn btn-primary btn-small"><i class="icon-chevron-down icon-white"></i> Gravar</button>
    </p>
</form>

{% endblock %}